# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1：检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

        # 步骤 2：设置 Dart/Flutter 环境
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          flutter: true

      # 步骤 3：安装依赖
      - name: Install dependencies
        run: flutter pub get

      # 步骤 4：运行测试
      - name: Run tests
        run: flutter test

      # 步骤 5：发布到 pub.dev
      - name: Publish package
        run: flutter pub publish --force
        env:
          PUB_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}  # 注入令牌
